### ISSUE TITLE
Error: [ng:areq] Argument 'StrapSelectController' is not a function, got undefined

### ISSUE THREAD

**Issue by nicklasb** [networknt/angular-schema-form-strapselect#1] opened 2015-01-12 11:57 UTC
I am not sure how far you are into the implementation, I tried to run it and while Single Select Static and Multi Select Static seem to work, the dynamic versions seems not to. 

I suppose I need to set up som backend at api/rt to satisfy that, but this error seems earlier. I have installed all bower_components I could find, not sure where this is being raised. Haven't looked very carefully either, as I don't know if its debugging time yet.

**Comment by stevehu** [comment] 2015-01-12 12:10
It is working within Light Framework and the back end serves the dynamic dropdowns. It has to be under lightApp so that the controller can be lazy loaded and registered. I will write up some thing and build a demo. Stay tuned.

Steve

**Comment by nicklasb** [comment] 2015-01-12 12:18
Ok. 
Is https://github.com/networknt/light this what you are talking about?
Will that be a dependency for the component or can the component be used without it?

**Comment by stevehu** [comment] 2015-01-12 12:47
It can be used independently but you have to save  the providers when angular bootstraps. If you look into the source code you can see there is a dynamic field level controller does the ajax call and you app does not know the controller before the form is loaded.

**Comment by nicklasb** [comment] 2015-01-12 20:22
Ok. Just saying, though..From my perspective, an example with a new component that at the same time implements a new framework I don't know anything about is not very useful. It is very difficult for me to see what is necessary or not necessary for me to do to use or contribute to the component.

An example that is as clean as possible that just demonstrates the principles would be far more usable to me, as it is now, I didn't get much at first, to be honest..

**Comment by stevehu** [comment] 2015-01-12 22:17
I understand your frustrations. As I said in my first post, I will build a demo/example and write the detail up. It takes some time and I am so busy now. I didn't expect someone to use it at this stage as it is still working in progress to be utilized outside of my framework. As of now, I can point out the right location in my source code and you figure it out by yourself or you have to come back later when it is ready. 

Steve

**Comment by nicklasb** [comment] 2015-01-13 11:25
Thats great! 
Yes, it takes a lot of time these things, they truly do, thanks for doing it nonetheless.
.
I will probably do something else for about a week, will check this out after that, but if you could give me some pointers of where to put my stuff, it would be great. I am not totally getting the template cache vs. providers and so on.
Anyway  suppose you'd be having to write something down about it sooner or later anyway so that effort wouldn't be wasted on me alone.. :-)

**Comment by stevehu** [comment] 2015-01-18 17:20
Hi @nicklasb 
I have uploaded a video regarding to strapselect and uiselect for angular schema form and you can watch it at http://youtu.be/B-TjSF81uuU

Let me know if you still have questions. Thanks.

**Comment by nicklasb** [comment] 2015-01-18 17:28
Cool!
I'll check it out tonight(cet+1), I promise to be at my stupidest. :-)

**Comment by nicklasb** [comment] 2015-01-18 23:05
Ok, some feedback:
1. As I understand it, it is OK to extend JSON schema with new attributes, however adding new values to format is a bit dangerous; "Implementations MAY add custom format attributes. Save for agreement between parties, schema authors SHALL NOT expect a peer implementation to support this keyword and/or custom format attributes."
As this is with regards to a pure strapselect UI feature and one of the points of JSON schema is to be able to use the same schema "behind the scenes", I wouldn't put that in the schema, but in the schema form. If the same backend is to used by different front ends, that format value would not be usable, and also, it could raise an error when validated by some other validator. In other words, it feels like good form to store UI settings in schemas as long as they are general, as "order" or "layout". Less to to store values like "nicklasb_component" or strapselect. Just my 2 cents.
2. In strap*selectdynamic.html, why not have:

    $scope.getItem = function(category, name) {
        readOnly: true
        category = category;
        name = name;
     };
instead of the current partial initiation? 
And why not also drop the $scope.fetchResult(); line and instead call fetchResult() directly from the ng-init?
Actually, it would be even clearer to define JSON object in fetchResult itself and not even have a getItem? I mean, it is so little code and I sort of fail to see they point of that extraction?

3. There is a bit too much to expect that the user should grasp three concepts at once; a) Light, b) strapselect c) the structure of theexample. Also, there is some Java code getting mention too which is quite confusing, 
I would start by first describing, as you did, a little bit about schema form, but then start with describing the example application. Because "form" and "forum" are two very similar words one at first doesn't really get the point. After that the second part and then what you started with.

4. I am building a Python backend on MongoDB, so I will probably not use light. Also, if this component is going to get any traction, I would not mix the two projects up too much. Light seems cool, but complete modularity is *never* bad for any open source project in my mind. I will make an implementation against my backend and then make an simple example that works against a mock-backend. And personally, I will see if I can fire the population on ng-click instead of init. And maybe then you can see what you think of it and decide how you want to do architectually.
5. Damn the multiselect components(also the UI) looks good. I was salivating. :-)

**Comment by stevehu** [comment] 2015-01-18 23:16
Thanks for the feedbacks. I totally agree it should be independent;
however, given limited time, I could not make it. It seems you know how it
works and I am hoping you can fork it and make it usable outside of Light
Framework. More people will benefit in that way.

Best regards,

Steve

On Sun, Jan 18, 2015 at 6:05 PM, Nicklas Börjesson <notifications@github.com

**Comment by nicklasb** [comment] 2015-01-18 23:18
I will try and see what I can do. I have some time for it soon. Either way, great work so far!

**Comment by stevehu** [comment] 2015-01-18 23:22
Thanks lot. It will be great if you could make ui-select works the same way
as strapselect:)

On Sun, Jan 18, 2015 at 6:18 PM, Nicklas Börjesson <notifications@github.com

**Comment by nicklasb** [comment] 2015-01-18 23:34
Yep, that also is a good looking component. :-)

**Comment by nicklasb** [comment] 2015-02-10 14:58
Hi,
I am not sure if I told you, but chengz, had no time for this either, so I am taking over the project.

I have now fixed the packaging, naming, documentation and so on and made a statement about it: 
https://github.com/Textalk/angular-schema-form/issues/246

Also I made an official repo under my organisation:
https://github.com/optimalbpm/angular-schema-form-strapselect

I am not completely sure, but you will likely have to either rename or remove this repo for them not to conflict in the bower database. If anything, it can be confusing and you'll end up getting issues registered on this repository.

**Comment by nicklasb** [comment] 2015-02-11 11:35
Ok, I have now checked, I couldn't register my repository for the package, because it conflicted with the registration of this one. It seems that you don't need to delete the repository, but  you need to unregister the repository so I can register the new repo URL.
Here is how to do it:
http://bower.io/docs/creating-packages/#unregister

Would be great if you could to this as soon as possible, as people will be continuing to install from your repository until it is done, the fever we need to assist in migrating the better.

**Comment by stevehu** [comment] 2015-02-11 11:40
I can not do that before testing you code with my framework. Why not use another name of you own?

Sent from my Sony Xperia™ smartphone

---- Nicklas Börjesson wrote ----

**Comment by nicklasb** [comment] 2015-02-11 12:12
If you feel like that, I will have to respect that.

The reasons are:
1. The correctly formatted of the add-on  is
angular-schema-form-strapselect, changing the name to something else would
mean a lot of searching and replacing, changing the name of the repo and
spreading the word. The schema form admins have already tweeted about the
add-on. And then I would have to do it back again.
2. As long as the wrong repository is listed on the schema-form web site,
people will keep using that version, which isn't very good. I have done
significant work the last days. Also, there is almost no documentation and
when they have negotiated that, the first thing they will have to do then
is to change their application for it to work with the new version.

**Comment by nicklasb** [comment] 2015-02-15 10:02
Do you know when you have time to look at this? 
It would be good to have an actual example against a live backend, like yours, as I won't be having anything like that done for at least month or two.
Also, the videos you made, it seems like mostly, they are still applicable, aside from where they say that the settings are store, perhaps just that part could be changed?

**Comment by nicklasb** [comment] 2015-02-15 10:14
I am thinking that it should be really easy to do for you, only thing you would have to do would be using the http_post to "api/rs" using these parameters in the form:

     {
       "key": "multiselectdynamic",
       "type": 'strapmultiselectdynamic',
       "options": {
           "http_post": {
               "url" : "api/rs",
               "parameter": { "readOnly" : true, "category": "forum", "name": "getForumDropdown"}
           }
       }
     },

**Comment by stevehu** [comment] 2015-02-21 16:56
Hi Nicklas,

I finally got some time to clone your repo and test it. The code base is
very good and I have deployed a REST API endpoint for you to call from
http_get and http_post.

get:
http://www.networknt.com/api/rs?cmd={
"category":"demo","name":"getDropdown","readOnly":true}

post:
http://www.networknt.com/api/rs
with body of below.
{"category":"demo","name":"getDropdown","readOnly":true}

Once the remote dropdown is working, I can merge your code into my repo and
release a new version. Or I will give you admin for my repo and you can
maintain it on your own. I cannot give up the project registration name as
my framework depends on it.

Thanks,

Steve

On Sun, Feb 15, 2015 at 5:14 AM, Nicklas Börjesson <notifications@github.com

**Comment by nicklasb** [comment] 2015-02-21 19:21
Good.I will make an example for that. Hovever:
1. I would strongly recommend against cloning the code and merge. That would be doing the same thing you did first, to break the fork structure. Rather just rename your existing networknt/angular-schema-form-strapselect to networknt/angular-schema-form-strapselect-deprecated and fork my repository into a new networknt/angular-schema-form-strapselect. It is to my understanding "how its done" on github, and also that will keep the history understandable and git more healthy and the repository maintainable. After all, the major work with this component was made by Chengz and it is a fork, would not look good if that didn't show in the tree.
2. No, I am a firm believer in doing as little and having as few permissions as possible. :-) 
So if you feel that you want to helm the project, you should. I was under the impression that you didn't have any time to handle the responsibilities and stepped up because you couldn't.
3. Just saying, If your framework depends on "networknt/angular-schema-form-strapselect", it shouldn't, it should depend on "angular-schema-form-strapselect". That way, it doesn't matter what repo the registration points to.

**Comment by nicklasb** [comment] 2015-03-02 18:44
Hi, just tried to implement it, and I couldn't make it work, since you need to add a Access-Control-Allow-Origin header to the web server, or the browser won't allow the component access to the results.
It goes something like this:  
http://stackoverflow.com/questions/5008944/how-to-add-an-access-control-allow-origin-header

**Comment by stevehu** [comment] 2015-03-02 21:23
I totally forgot about it. I will get my server updated and let you know.
Thanks,
Steve

**Comment by nicklasb** [comment] 2015-03-03 06:57
No problem.

BTW, this is off topic, but I saw that you have OrientDB as the backend for your framework, what are your experiences? Asking, since I am using MongoDB for my Python-framework, but is considering to expand so it also supports OrientDB. It is not everywhere like MongoDB yet, but seems to have much of the functionality one misses from the SQL servers.

**Comment by stevehu** [comment] 2015-03-03 11:44
So far, my experience with Orientdb is positive. The community is active
but not as big as Mongo; however, the graph db is so powerful that changes
the way of modelling. There are some bugs that you have to work around and
documentation is poor. Also, the learn curve of graph db is steep:) but I
think it is the future.

Have fun.

Steve

**Comment by damogallagher** [comment] 2015-03-10 20:16
Hey guys

Just wondering where this conversation left off?
I am using UI Select at the minute for single and multi selects.
For Dynamic multi select - UISelect is working well at the minute

Steve - you recommended StrapSelect for Dynamic Single Select but i tried the sample in the git repo and unfortunately its not working.

Based on your conversation with Nick - is there an update due?

Thanks
Damien

**Comment by damogallagher** [comment] 2015-03-12 17:05
Hi guys. just wondering if there is any update on this?

Cheers
Damien

**Comment by stevehu** [comment] 2015-03-12 17:08
Not yet.

**Comment by nicklasb** [comment] 2015-03-12 18:05
@damogallagher : No, you are right, the version in this repository isn't the working version.
Meanwhile, you can try the one in my repo at https://github.com/nicklasb/angular-schema-form-strapselect

That is the repo we were discussing above, the one that this should become.

@stevehu : "Not yet" seems like a stellar piece of redundant information. :-)
But seriously, I am sort of also waiting here, soon I will make some more contributions, amongst other thing I will extend the examples to include a connection against a server I have running a python-backend* as a live example is sorely needed. And perhaps not only one. 
Do you have any approximate idea when you will get your server in order?

* We all seem to make backends meet, at least. Tihi.

**Comment by stevehu** [comment] 2015-03-12 21:16
@Nicklas my server is based on my own framework and I am planning to add
cors support to it this weekend. I have changed the framework a lot
recently and I need to test it out before deploying to prod. The earliest
would be 4 weeks later I guess. I would encourage you to use your own
server if possible. Also I have another 10 repos to suuport:-)

Thanks,
Steve

**Comment by nicklasb** [comment] 2015-03-12 21:23
Could you contact me personally? My username on google mail is nicklasb.

**Comment by nicklasb** [comment] 2015-03-12 23:23
Sorry, made a mistake, I was referring to: https://github.com/OptimalBPM/angular-schema-form-strapselect

**Comment by nicklasb** [comment] 2015-03-13 10:39
@damogallagher : You saw that I first mistakenly pointed you the wrong repo, right?

**Comment by damogallagher** [comment] 2015-03-13 10:56
Hi Nick - yeah I saw that - thanks for getting back to me on it :)

**Comment by nicklasb** [comment] 2015-03-14 07:57
Good. If you find any problems, you can file an issue on that repo instead and I'll see it.

**Comment by stevehu** [comment] 2015-03-15 13:36
@nicklasb I have merged your code and it works on my local server that supports cors. You can see the code pointing to http://example:8080/api/rs in app.js. I am still testing my server and planning to release to production within a week or two. Also, with strets123's help, the defect in ui-select is fixed and he added more features (like add a new tag, group by and search by desc etc.). In addition, I have merged your code into the ui-select so that it can fetch result from callback, asyn file and http post/get. It is usable now from master branch and the only thing is to switch the url to my production url to release another version. 

Thanks a lot for your help!!!!

**Comment by nicklasb** [comment] 2015-03-15 23:27
Ok...but it seems like *a lot* of stuff is missing, like the examples and the documentation. And most importantly, all commit history and branching information is gone. 
So who has actually done what is now impossible to see. 

Why not just make a branch of my repo and then do *no* merging at all for the strapselect?

**Comment by stevehu** [comment] 2015-03-15 23:29
@nicklasb I couldn't find your pull request and your repo anymore as of
yesterday. That is why I have merged manually from a copy of my local
folder and move your code from strapselect to uiselect manually.

On Sun, Mar 15, 2015 at 7:27 PM, Nicklas Börjesson <notifications@github.com

**Comment by nicklasb** [comment] 2015-03-15 23:34
Then you have the badly designed and old code and is something like 50 commits behind.
It is the repo above, I accidentally gave the wrong one to @damogallagher but corrected that in a later message.

Do like this, this will take you about 5 minutes:
1. Rename networknt/angular-schema-form-strapselect into networknt/angular-schema-form-strapselect-deprecated.
2. Fork https://github.com/OptimalBPM/angular-schema-form-strapselect and call it networknt/angular-schema-form-strapselect.
3. Done!

**Comment by nicklasb** [comment] 2015-03-15 23:35
I didn't make a pull request as networknt/angular-schema-form-strapselect was incorrectly "forked".

**Comment by nicklasb** [comment] 2015-03-15 23:43
I can then remove my repo(or perhaps rename it to do-not-use).

There is another very important issue here, and that is about giving cred to contributors. To in any way hide the commit history is not only unsafe and bad practice, but can also be understood as trying to inflate one's own contribution. I know that is not your intent, you have enough work to show for already it seems, but I would be careful about the sensitivities of other contributors. Just saying.

**Comment by nicklasb** [comment] 2015-03-16 00:20
Sorry, by the way, but one can never go solely by the email notifications on Github. 

People, myself included, constantly updates the responses, so what is in the e-mails aren't necessarily correct. Also, people don't realize that changes in responses doesn't result in e-mails, that is why I made the correction above.

**Comment by nicklasb** [comment] 2015-03-18 18:51
@stevehu : You seem to continue on this road? 

Could you please contact med privately via gmail? nicklasb /at\ g m a i l d ot com

**Comment by stevehu** [comment] 2015-03-19 11:49
@nicklasb as we have discussed I have reverted your change because it breaks my code base. There are two issues.
1. You moved my controller from strapselect field to schemaForm there are cross fires between forms if you have more than two forms in your application. It does't matter two forms are on the same page or not. 
2. to have customized controller for each form to support remote call is not right by design in the first place. The logic can be encapasulted in strapeselect field and the field level controller can be registered when form is loaded as I did. 

Thanks.

**Comment by nicklasb** [comment] 2015-03-19 12:14
1. I cannot reproduce that, do you have an example?
2. You don't have to. The http_post/http_get is all in the form. No
customization needed. That is why I proposed http_jsonp.

//Nicklas

On Thu, Mar 19, 2015 at 12:49 PM, stevehu <notifications@github.com> wrote:

> @nicklasb <https://github.com/nicklasb> as we have discussed I have
> reverted your change because it breaks my code base. There are two issues.
> 1. You moved my controller from strapselect field to schemaForm there are
> cross fires between forms if you have more than two forms in your
> application. It does't matter two forms are on the same page or not.
> 2. to have customized controller for each form to support remote call is
> not right by design in the first place. The logic can be encapasulted in
> strapeselect field and the field level controller can be registered when
> form is loaded as I did.
>
> Thanks.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/networknt/angular-schema-form-strapselect/issues/1#issuecomment-83521901>
> .
>



-- 
Med vänliga hälsningar/Kind regards,
Nicklas Börjesson

**Comment by nicklasb** [comment] 2015-03-19 12:58
And (in this thread), then, my proposed solution to #2 would be this:
"options":{
    "http_jsonp": {
        "url": "networknt.com/lightBackend"
        "parameter": { "category": "whatever", "something_else":"that"}
    }
}

This would then make cors-compatibel http.jsonp()-call to another domain.
Perhaps most of the other callback-styles could be scrapped as their form entries are defined in runtime and replaced by one that gets all parameters from the form.

**Comment by nicklasb** [comment] 2015-03-19 13:03
With regards to #1, the example does not need to be a working one, I just need to look at the code, and then I can replicate the setup and hopefully recreate and fix the problem. But send it to my E-mail instead. 

The thing is that the code as it looks here is very geared towards light, has no working test, form stuff in the schemas and so forth. I would simply not be interested in re-doing the quite significant work I have done. To fix the any bugs in my implement seems like a *far* easier approach.

**Comment by stevehu** [comment] 2015-03-19 23:49
@nicklasb I tried to reproduce the issue and give you a screenshot but my code base has reverted back. Basically, my login page userId filed is rendered as a strapselect dropdown and it should be a normal string text field. 

If you want to get it fixed, you can use my server for CORS REST API as following for post and get. It is open to everyone without asking for oauth2 jwt token. Thanks.

     {
       key: 'multiselect_get',
       options: {
           http_get: {
               url : "http://www.networknt.com/api/rs?cmd={\"category\": \"demo\", \"name\": \"getDropdown\", \"readOnly\": true}"
           }
       }
     },
     {
       key: 'multiselect_post',
       options: {
           http_post: {
               url : "http://www.networknt.com/api/rs",
               parameter: { category: "demo",  name: "getDropdown", readOnly: true}
           }
       }
     },

**Comment by nicklasb** [comment] 2015-03-20 06:24
Ok, I'll try some more..

//Nicklas

On Fri, Mar 20, 2015 at 12:49 AM, stevehu <notifications@github.com> wrote:

> @nicklasb <https://github.com/nicklasb> I tried to reproduce the issue
> and give you a screenshot but my code base has reverted back. Basically, my
> login page userId filed is rendered as a strapselect dropdown and it should
> be a normal string text field.
>
> If you want to get it fixed, you can use my server for CORS REST API as
> following for post and get. It is open to everyone without asking for
> oauth2 jwt token. Thanks.
>
>  {
>    key: 'multiselect_get',
>    options: {
>        http_get: {
>            url : "http://www.networknt.com/api/rs?cmd={\"category\": \"demo\", \"name\": \"getDropdown\", \"readOnly\": true}"
>        }
>    }
>  },
>  {
>    key: 'multiselect_post',
>    options: {
>        http_post: {
>            url : "http://www.networknt.com/api/rs",
>            parameter: { category: "demo",  name: "getDropdown", readOnly: true}
>        }
>    }
>  },
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/networknt/angular-schema-form-strapselect/issues/1#issuecomment-83811837>
> .
>



-- 
Med vänliga hälsningar/Kind regards,
Nicklas Börjesson

**Comment by nicklasb** [comment] 2015-03-20 11:43
So I've checked out your login page, and as I understand it, your usage of schema-form is pretty far from how it is normally used. 

You seem to have an array containing a separate form for each field within the same schema form instance, am I right? As far as I can see how schema-form seem to be designed and documented, , schemas and forms are supposed to be 1 to 1, not 1 to many..at the same time.

I am sure it is possible that this can work under certain circumstances, however it would appear to me that even the slightest change to how schema-form works will break it. And crossfiring, yes that could quite possibly be a problem. 

I am not completely sure why you use it at all there, it doesn't seem to add much to the functionality of the login page. 

I will add calls to your backend to the examples now.

**Comment by nicklasb** [comment] 2015-03-20 12:15
Ok, It seems to work getting data using a normal post from your site, so JSONP might not be necessary.

I have two minor issues though:
1. The result is from value/label and the strapselect has value/name. But in actuality, a HTML options have value and a text property. I would propose that we change both strapselect to use name/text as well, that would make it the easiest to for users to understand. And it would be according to standards.  You would have to change your backend to send name/text, too. On the other hand, that would be more in tune with the internetz. 
What do you think?

2. No matter how I try, the get-url you provided returns "invalid_command", there seems to be something wrong.

**Comment by damogallagher** [comment] 2015-03-25 22:01
Hey guys

Just wondering is this version of the plugin now ready to use?
Sorry I got pulled off on something else for a few weeks 

Cheers
Damien

**Comment by nicklasb** [comment] 2015-03-25 22:11
Hi, no worries.

It turned out that we had too many different ideas of how to move on, so I have decided to continue with my own fork, and Steve will continue with his(this one).

You may choose either, you can find mine at: 
https://github.com/OptimalBPM/angular-schema-form-dynamic-select

**Comment by damogallagher** [comment] 2015-03-25 22:12
Ah right ok
What stage is your version of the plugin at compared to Steves?

This is a bit like the nodejs wars?

**Comment by nicklasb** [comment] 2015-03-25 22:21
Haha....no, there are no wars, just differing opinions on how to do what, where and where to go.. 
If they differ too much in a project, there will just be a lot of extra work done for nothing, and then a fork is the natural way to go. 

In this case it is not even a fork, mine is acturally forked from chengz:s original code and the additions Steve made in this repo were merged in(as this repo isn't technically a fork but a copy).

With regards to how well it works, it works well as far as I know. If it doesn't work for you, create an issue and we'll see what we can do.

**Comment by nicklasb** [comment] 2015-03-25 22:25
If you want more information about my fork, we can discuss this in that repo instead. 
I am not really comfortable with "marketing" *my* fork in steves repo. 
We are all trying to do something good, you know?

**Comment by damogallagher** [comment] 2015-03-25 22:26
I completely understand nick - fair play to both of ye. Hopefully both tools benefit loads of people
Ill have a look and let you know if i have questions

**Closed** 2015-04-16 23:55 UTC
